site_name:        TLPM.jl
repo_url:         https://github.com/MLackner/TLPM.jl
site_description: Documentation for the TLPM.jl Julia package
site_author:      Michael Lackner

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

nav:
  - Home: index.md